### ISSUE TITLE
Unable to install httpie via Chocolatey

### ISSUE THREAD

**Issue by ChukwunonsoFrank** [httpie/httpie#1522]
I tried installing Httpie on my Windows machine but I spits out this error everytime.

![image](https://github.com/httpie/httpie/assets/62689166/06629108-4223-43a7-9f25-ef4a35e3dbd1)

I am running Powershell 7 on Windows 11 Version 22H2 (OS Build 22621.1555)

**Comment by ChukwunonsoFrank** [comment]
any help with this @jakubroztocil

**Comment by jakubroztocil** [comment]
@ChukwunonsoFrank we’ll look into it 👀  It may take a while, though, so in the meantime, I recommend installing it using pip: https://httpie.io/docs/cli/pypi

**Comment by gianpaolof** [comment]
hi @jkbrzt same problem of the user. I have also tried with pip, after installing MS build tools, but I got this error:

 C:\Users\gianp\AppData\Local\Temp\pip-build-env-avrea4bl\overlay\Lib\site-packages\setuptools\command\build_py.py:204: _Warning: Package 'multidict._multilib' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'multidict._multilib' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'multidict._multilib' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'multidict._multilib' to be distributed and are
              already explicitly excluding 'multidict._multilib' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        !!
        check.warn(importable)
      copying multidict\__init__.pyi -> build\lib.win-amd64-cpython-312\multidict
      copying multidict\py.typed -> build\lib.win-amd64-cpython-312\multidict
      running build_ext
      building 'multidict._multidict' extension
      creating build\temp.win-amd64-cpython-312
      creating build\temp.win-amd64-cpython-312\Release
      creating build\temp.win-amd64-cpython-312\Release\multidict
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Python312\include -IC:\Python312\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /Tcmultidict/_multidict.c /Fobuild\temp.win-amd64-cpython-312\Release\multidict/_multidict.obj -O2
      _multidict.c
      C:\Python312\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for multidict
Failed to build multidict
ERROR: Could not build wheels for multidict, which is required to install pyproject.toml-based projects

**Comment by zBoschi** [comment]
Hey! I got the same errors while trying to install using chocolatey and pip through PowerShell.
PS Version:  5.1.22621.2428
Windows 11 Version 22H2

**Comment by joseroblesv** [comment]
I got the same error while trying to install it using Chocolatey through PowerShell
PS Version: 5.1.22621.2506
Windows 11 Version 22H2

------------------------------------------------

ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop:   error: subprocess-exited-with-error
The install of httpie was NOT successful.

**Comment by omri-ratson** [comment]
**Same issue here**

Trying to install `httpie` with pip didn't work either, the logs are not providing any useful information.

I tried to re-install `chocolatey` and `pip` just in case maybe I messed something up on my system but it didn't fix the issue.
PS version: 7.4.0
Windows 11 version 22H2.

**Comment by Fawaz0450** [comment]
Looks like this error is a Windows 11 thing cos I'm getting the same errors to, might have to downgrade back to windows 10 and try installing httpie again.

**Comment by joseroblesv** [comment]
> Looks like this error is a Windows 11 thing cos I'm getting the same errors to, might have to downgrade back to windows 10 and try installing httpie again.

No need to downgrade, I fixed it with the pull request that appears above
https://github.com/httpie/cli/pull/1531

**Comment by Ousret** [comment]
Glad to see the PR helped. Could you give us insight as if you've encountered any issues? Or-- simply put a feedback, positive or negative. Feedbacks can improve the level of confidence for the given PR.

Regards,

**Comment by joseroblesv** [comment]
The feedback is positive. The issue was fixed with that PR.

**Comment by Ousret** [comment]
The PR does not only "fix" this issue but go way beyond that, with HTTP/2, and HTTP/3 support for example. So that's why we are looking for feedbacks. But, I'll suspect that you encountered none if I am not mistaken. Great!

**Comment by joseroblesv** [comment]
Sorry about not being able to provide more feedback, since I just used httpie while following a tutorial

**Comment by Ousret** [comment]
Perfect. It's more than enough for a feedback.

**Comment by Neutrino-Sunset** [comment]
So did the fix not get deployed or what? Still getting the exact same error.

**Comment by Night3y3** [comment]
![Image](https://github.com/user-attachments/assets/c1026358-13c9-4dd6-b849-08fc3c5f9f94)

Getting this error

Windows 11
